### PR TITLE
Allow adding of arbitrary non-python-package dirs

### PR DESCRIPTION
**Pull request by jamesjuran2**
Hi Rob, here's the change I mentioned to support including extra directories in a package. We've been using this successfully for quite a while. @herrewig did the actual work here, I'm just doing the easy part of sending it.

### CODE REVIEW

**Comment by herrewig** [comment]
I'd recommend against merging this. This can be achieved with MANIFEST.in, but I didn't know about that when I wrote this.

**Comment by jamesjuran2** [comment]
OK, I'll close this and not fix the tests then. @robdennis, if you find this useful for some reason still let me know or just feel free to grab it.

**Comment by robdennis** [comment]
> I'd recommend against merging this. This can be achieved with MANIFEST.in, but I didn't know about that when I wrote this.

Yeah, this is the number one thing I've ended up forgetting when making a new library.

**Comment by robdennis** [comment]
Closing this seems fine for now, if this generally idea needs to be looked at again, we'll reopen :). Thanks.

**Pull request closed without merging**
